// Code generated by scripts/generate_provider_config.go; DO NOT EDIT MANUALLY.
package dns

import "github.com/crossplane/upjet/pkg/config"

// Configure adds configurations for dns group.
func Configure(p *config.Provider) {

	// https://github.com/cloudflare/terraform-provider-cloudflare/apis/dns/v1alpha1.Record
	p.AddResourceConfigurator("cloudflare_record", func(r *config.Resource) {
		r.Kind = "Record"
		r.ShortGroup = "dns"

		r.References["zone_id"] = config.Reference{
			TerraformName: "cloudflare_zone",
			RefFieldName: "ID",
		}
	
	})

	// https://github.com/cloudflare/terraform-provider-cloudflare/apis/dns/v1alpha1.DNSSEC
	p.AddResourceConfigurator("cloudflare_zone_dnssec", func(r *config.Resource) {
		r.Kind = "DNSSEC"
		r.ShortGroup = "dns"

		r.References["zone_id"] = config.Reference{
			TerraformName: "cloudflare_zone",
			RefFieldName: "ID",
		}
	
	})
}