// Code generated by scripts/generate_provider_config.go; DO NOT EDIT MANUALLY.
package account

import "github.com/crossplane/upjet/pkg/config"

// Configure adds configurations for account group.
func Configure(p *config.Provider) {

	// https://github.com/cloudflare/terraform-provider-cloudflare/apis/account/v1alpha1.Account
	p.AddResourceConfigurator("cloudflare_account", func(r *config.Resource) {
		r.Kind = "Account"
		r.ShortGroup = "account"
	})

	// https://github.com/cloudflare/terraform-provider-cloudflare/apis/account/v1alpha1.APIToken
	p.AddResourceConfigurator("cloudflare_api_token", func(r *config.Resource) {
		r.Kind = "APIToken"
		r.ShortGroup = "account"
	})
}