apiVersion: dns.cloudflare.crossplane.io/v1alpha1
kind: DNSSEC
metadata:
  annotations:
    meta.upbound.io/example-id: dns/v1alpha1/dnssec
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    zoneIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: zone.cloudflare.crossplane.io/v1alpha1
kind: Zone
metadata:
  annotations:
    meta.upbound.io/example-id: dns/v1alpha1/dnssec
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    zone: example.com
