// Code generated by scripts/generate_provider_config.go; DO NOT EDIT MANUALLY.
package zone

import "github.com/crossplane/upjet/pkg/config"

// Configure adds configurations for zone group.
func Configure(p *config.Provider) {

	// https://github.com/cloudflare/terraform-provider-cloudflare/apis/zone/v1alpha1.Zone
	p.AddResourceConfigurator("cloudflare_zone", func(r *config.Resource) {
		r.Kind = "Zone"
		r.ShortGroup = "zone"

		r.References["account_id"] = config.Reference{
			TerraformName: "cloudflare_account",
			RefFieldName: "ID",
		}
	
	})
}
